
service: import-service-api
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  profile: default
  stage: dev
  environment:
      SQS_URL: ${env:SQS_URL}
  httpApi:
    cors:
      allowedOrigins:
        - https://d3daouilse61ba.cloudfront.net
      allowedMethods:
        - GET
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 's3:ListBucket'
      Resource: 'arn:aws:s3:::import-service-storage'
    - Effect: Allow
      Action:
        - 's3:*'
      Resource: 'arn:aws:s3:::import-service-storage/*'
    - Effect: Allow
      Action:
        - 'sqs:*'
      Resource: 'arn:aws:sqs:us-east-1:735574760852:catalogItemsQueue'

functions:
  importProductsFile:
    handler: functions/importProductsFile.importProductsFile
    events:
      - httpApi:
          path: /import
          method: GET

  importFileParser:
    handler: functions/importFileParser.importFileParser
    events:
      - s3:
          bucket: import-service-storage
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
